apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: congress
  namespace: apigee
  labels:
    name: congress
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: congress
    spec:
      containers:
      - image: thirtyx/congress:dev
        imagePullPolicy: Always
        name: congress
        env:
        - name: CONGRESS_ISOLATE_NAMESPACE
          value: false
        - name: CONGRESS_EXCLUDES
          value: "default,kube-system,apigee,apigee-jenkins,calico-system,guardians"
        - name: CONGRESS_SELECTOR
          value: "Runtime=shipyard"
        - name: CONGRESS_IGNORE_SELECTOR
          value: "Runtime=other"
