apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: congress
  namespace: apigee
  labels:
    name: congress
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: congress
    spec:
      containers:
      - image: thirtyx/congress:0.1.2
        imagePullPolicy: Always
        name: congress
        env:
        - name: CONGRESS_ISOLATE_NAMESPACE
          value: "true"
        - name: CONGRESS_EXCLUDES
          value: "kube-system,apigee,calico-system"
        - name: CONGRESS_IGNORE_SELECTOR
          value: "congress=exclude"
